auto: true
title: "科技空间"
public_url: "http://shuihelan.github.com"
keywords: "mono, ios, android, silverlight, asp.net mvc, asp.net web api, nhibernate, c, sql server, xml, linux, mac osx"
owner:
  name: "廖光东"
  mail: "1849805334@qq.com"
disqus:
  short_name: "shuihelan-github"
paginate: 10
exclude: [start-jekyll.bat, Github.sln, Github.v11.suo]